AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Oracle Application Administration Toolbox by the Oracle Applications on AWS team
  This is the root template
  
Parameters:
  notificationEmail:
    Type: String
    Default:  youremail@yourdomain.com
    Description: >
      Your email address to be used to send out dummy emails from EventBridge rule & scheduler. 
      Need to add and then validate it from AWS Console --> Amazon SES --> Verified Identities. 
      Before validation completes, the Lambda function sending email shall fail.

Resources:
  OAATShared: ## E-Business Suite child stack
    Type: AWS::Serverless::Application
    Properties:
      Location: oaat-shared/template.yaml

  eBusinessSuite: ## E-Business Suite child stack
    Type: AWS::Serverless::Application
    Properties:
      Location: ebiz/template.yaml
      # Parameters: -
        # oaatBucketName: !GetAtt OAATShared.Outputs.MainBucketName
        # logBucketName: !GetAtt OAATShared.Outputs.LogBucketName
        # oaatEventBusName: !GetAtt OAATShared.Outputs.EventBusName

  # JDE: ## JDEdwards child stack
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: jde/template.yaml

  # PeopleSoft: ## PeopleSoft child stack
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: peoplesoft/template.yaml


